---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telepresence-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telepresence-admin-role
rules:
  - apiGroups:
      - ""
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "create", "delete", "watch"]
  - apiGroups:
      - ""
    resources: ["services"]
    verbs: ["get", "list", "update", "create", "delete"]
  - apiGroups:
      - ""
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups:
      - "apps"
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "update", "create", "delete", "watch"]
  - apiGroups:
      - "getambassador.io"
    resources: ["hosts", "mappings"]
    verbs: ["*"]
  - apiGroups:
      - ""
    resources: ["endpoints"]
    verbs: ["get", "list"]
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups:
      - ""
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups:
      - ""
    resources: ["secrets"]
    verbs: ["get", "create", "list", "delete"]
  - apiGroups:
      - ""
    resources: ["serviceaccounts"]
    verbs: ["get", "create", "delete"]
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "create", "delete"]
  - apiGroups:
      - ""
    resources: ["nodes"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telepresence-clusterrolebinding
subjects:
  - name: telepresence-admin
    kind: ServiceAccount
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: telepresence-admin-role
  kind: ClusterRole
